{"uid":"4b4757e66a1912dae1a509f688f20b0f","children":[{"name":"Test defects","children":[{"name":"selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 1","children":[{"name":"test_send_and_delete_message_1_with_attachment[firefox]","uid":"5dd2aa5515fc383b","parentUid":"359adc3b20c3cd6e289fa31b85222924","status":"broken","time":{"start":1730129348357,"stop":1730129348357,"duration":0},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":true,"retriesCount":0,"retriesStatusChange":false,"parameters":["'firefox'"],"tags":["order(1)","@pytest.mark.usefixtures('setup')"]},{"name":"test_send_message_2_add_remove_reactions_and_cleanup[firefox]","uid":"665c79ae547c92c8","parentUid":"359adc3b20c3cd6e289fa31b85222924","status":"broken","time":{"start":1730129349554,"stop":1730129349554,"duration":0},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":true,"retriesCount":0,"retriesStatusChange":false,"parameters":["'firefox'"],"tags":["order(2)","@pytest.mark.usefixtures('setup')"]}],"uid":"359adc3b20c3cd6e289fa31b85222924"}],"uid":"bdbf199525818fae7a8651db9eafe741"}],"name":"categories"}